---
title: "DeepaK - PROJECT 1 607 Assigment"
author: "Deepak sharma"
date: "`r Sys.Date()`"
output:
   html_document:
    toc: true # table of content true
    toc_float: true
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
editor_options: 
  chunk_output_type: console
---

```{r}
library(stringr)
library(stringi)
library(knitr)
library(tidyverse)
library(dplyr)
library(kableExtra)

```
## Get the untidy data
```{r}
chessData=as.data.frame(read.delim("https://raw.githubusercontent.com/AsherMeyers/DATA-607/master/tournamentinfo.txt",header=FALSE,stringsAsFactors=FALSE,sep="|"))
 
chessData

#remove  11 column as it is of no use

chessData<-chessData[,-c(11)]

#to delete rows with -----

todelete<-seq(1,length(chessData$V1),3)
todelete
chessData<-chessData[-todelete,]
chessData

```
## Extract Important Data
```{r}


names_and_rounds <- chessData[seq(3, nrow(chessData), 2),]
names_and_rounds



State_and_Ratings = chessData[seq(4,nrow(chessData), 2),]
State_and_Ratings


row.names(chessData) <- NULL # remove row number counts


```
## Preview cleansed data
```{r}


n <- nrow(chessData)
t <-seq(3, n, by = 2) #counts by 2

kable(chessData) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>% 
  row_spec(t, background = "pink") %>% 
  scroll_box(width = "100%", height = "700px") 


```
## Extract Player Info and ratings
```{r}

names(State_and_Ratings)<-c("State","Rating")

 
# combine 2 rows into single row
chessData_new <- cbind(names_and_rounds, State_and_Ratings)
chessData_new


ratingList<-strsplit(chessData_new$Rating,split="->")
ratingList

extracted_names=chessData_new$V2

#extract player names
extracted_names<-stri_trim(extracted_names)
head(extracted_names)


#extract states names
extracted_states<-stri_trim(State_and_Ratings$State)
head(extracted_states)


#pre-rating

preratings <- unlist(stri_extract_all(State_and_Ratings$Rating, regex="[:]\\s+[[:digit:]]+"))
preratings <- unlist(stri_extract_all(preratings, regex="[[:digit:]]+"))
head(preratings)


#post-rating

postratings <- unlist(stri_extract_all(State_and_Ratings$Rating, regex="[>]\\s*[[:digit:]]+"))
postratings <- unlist(stri_extract_all(postratings, regex="[[:digit:]]+"))
head(postratings)


#round 1- split and get second value after split using tail
round1<-names_and_rounds$V4
round1<-sapply(strsplit(round1,split="\\s"), tail, 1)

head(round1)
#removed blank values
#round1<-stri_remove_empty(round1, na_empty = TRUE)


#round 1- split and get second value after split using tail
round2<-names_and_rounds$V5
round2<-sapply(strsplit(round2,split="\\s"), tail, 1)
head(round2)

#round 1- split and get second value after split using tail
round3<-names_and_rounds$V6
round3<-sapply(strsplit(round3,split="\\s"), tail, 1)
head(round3)

#round 1- split and get second value after split using tail
round4<-names_and_rounds$V7
round4<-sapply(strsplit(round4,split="\\s"), tail, 1)
head(round4)

#round 1- split and get second value after split using tail
round5<-names_and_rounds$V8
round5<-sapply(strsplit(round5,split="\\s"), tail, 1)
head(round5)

#round 1- split and get second value after split using tail
round6<-names_and_rounds$V9
round6<-sapply(strsplit(round6,split="\\s"), tail, 1)
head(round6)

#round 1- split and get second value after split using tail
round7<-names_and_rounds$V10
round7<-sapply(strsplit(round7,split="\\s"), tail, 1)
head(round7)


```
## Preview data
```{r}
id <- seq(1, 64, 1)
Chess_No_Avg<- data.frame(id, extracted_names, extracted_states,chessData_new$V3,
                          "Pre Rating" = as.numeric(preratings),
                          "Post Rating" = as.numeric(postratings), 
                          "Round 1" = as.numeric(round1),"Round 2" = as.numeric(round2), 
                          "Round 3" = as.numeric(round3), 
                          "Round 4" = as.numeric(round4), "Round 5" = as.numeric(round5),
                          "Round 6" = as.numeric(round6), "Round 7" = as.numeric(round7))

colnames(Chess_No_Avg) <- c ("Id", "Player Name", "State","Total Points", "Pre Rating",
                             "Post Rating", "Round 1","Round 2","Round 3","Round 4",
                             "Round 5","Round 6","Round 7")

glimpse(Chess_No_Avg)

head(Chess_No_Avg)

```

## Average rating calculation

```{r}
Avg_PreRating <- c()

for (i in Chess_No_Avg$Id){
  a <- Chess_No_Avg[Chess_No_Avg$'Round 1'==i, "Pre Rating"]
  a <- a[!is.na(a)]
  b <- Chess_No_Avg[Chess_No_Avg$'Round 2'==i, "Pre Rating"]
  b <- b[!is.na(b)]
  c <- Chess_No_Avg[Chess_No_Avg$'Round 3'==i, "Pre Rating"]
  c <- c[!is.na(c)]
  d <- Chess_No_Avg[Chess_No_Avg$'Round 4'==i, "Pre Rating"]
  d <- d[!is.na(d)]
  e <- Chess_No_Avg[Chess_No_Avg$'Round 5'==i, "Pre Rating"]
  e <- e[!is.na(e)]
  f <- Chess_No_Avg[Chess_No_Avg$'Round 6'==i, "Pre Rating"]
  f <- f[!is.na(f)]
  g <- Chess_No_Avg[Chess_No_Avg$'Round 7'==i, "Pre Rating"]
  g <- g[!is.na(g)]
  avg_rate <- mean(c(a, b, c, d, e, f, g))
  Avg_PreRating  <- c(Avg_PreRating, avg_rate)}
  Avg_PreRating
```
## Final Data Frame display
```{r}
#add calculations from above loop to initial Data Frame
Chess_No_Avg ["Opponent Pre Rating"] <- Avg_PreRating
FinalDataCSV  <- subset(Chess_No_Avg, select = c ("Id", "Player Name", "State",
                            "Pre Rating", "Opponent Pre Rating"))
FinalDataCSV %>%
  kable() %>%
  kable_styling()

```
## Write output to csv file
```{r}
#export dataframe to csv
write.csv(FinalDataCSV, "C:\\cuny education material\\Chess Tournament.csv")
 

```
